# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventana_principal.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1300, 846)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.PrincipalFrame = QtWidgets.QFrame(self.centralwidget)
        self.PrincipalFrame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.PrincipalFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.PrincipalFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.PrincipalFrame.setObjectName("PrincipalFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.PrincipalFrame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.TitutloFrame = QtWidgets.QFrame(self.PrincipalFrame)
        self.TitutloFrame.setStyleSheet("background-color: white;")
        self.TitutloFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.TitutloFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.TitutloFrame.setObjectName("TitutloFrame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.TitutloFrame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Liga = QtWidgets.QLabel(self.TitutloFrame)
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono SemiBold")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.Liga.setFont(font)
        self.Liga.setStyleSheet("color:black;")
        self.Liga.setObjectName("Liga")
        self.horizontalLayout_3.addWidget(self.Liga)
        self.verticalLayout.addWidget(self.TitutloFrame)
        self.General = QtWidgets.QFrame(self.PrincipalFrame)
        self.General.setStyleSheet("background-color: rgb(255, 247, 247);")
        self.General.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.General.setFrameShadow(QtWidgets.QFrame.Raised)
        self.General.setObjectName("General")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.General)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Barra = QtWidgets.QFrame(self.General)
        self.Barra.setStyleSheet("QFrame{background-color: rgb(42, 48, 81);}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color:balck;\n"
"}\n"
"\n"
"QPushButton{\n"
"    background-color: rgb(42, 48, 81);\n"
"    border-radius:8px;\n"
"}")
        self.Barra.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Barra.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Barra.setObjectName("Barra")
        self.gridLayout = QtWidgets.QGridLayout(self.Barra)
        self.gridLayout.setObjectName("gridLayout")
        self.BtnTabla = QtWidgets.QPushButton(self.Barra)
        self.BtnTabla.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono SemiBold")
        font.setPointSize(14)
        self.BtnTabla.setFont(font)
        self.BtnTabla.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BtnTabla.setObjectName("BtnTabla")
        self.gridLayout.addWidget(self.BtnTabla, 1, 1, 1, 1)
        self.BtnEquipo = QtWidgets.QPushButton(self.Barra)
        self.BtnEquipo.setMinimumSize(QtCore.QSize(0, 45))
        self.BtnEquipo.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono SemiBold")
        font.setPointSize(14)
        self.BtnEquipo.setFont(font)
        self.BtnEquipo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BtnEquipo.setObjectName("BtnEquipo")
        self.gridLayout.addWidget(self.BtnEquipo, 2, 1, 1, 1)
        self.BtnJornada = QtWidgets.QPushButton(self.Barra)
        self.BtnJornada.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono SemiBold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.BtnJornada.setFont(font)
        self.BtnJornada.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BtnJornada.setStyleSheet("")
        self.BtnJornada.setObjectName("BtnJornada")
        self.gridLayout.addWidget(self.BtnJornada, 0, 1, 1, 1)
        self.horizontalLayout_2.addWidget(self.Barra)
        self.Contenido = QtWidgets.QFrame(self.General)
        self.Contenido.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Contenido.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Contenido.setObjectName("Contenido")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.Contenido)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.Contenido)
        self.stackedWidget.setObjectName("stackedWidget")
        self.PaginaEquipos = QtWidgets.QWidget()
        self.PaginaEquipos.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.PaginaEquipos.setObjectName("PaginaEquipos")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.PaginaEquipos)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.TituloEquipos = QtWidgets.QFrame(self.PaginaEquipos)
        self.TituloEquipos.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.TituloEquipos.setFrameShadow(QtWidgets.QFrame.Raised)
        self.TituloEquipos.setObjectName("TituloEquipos")
        self.label = QtWidgets.QLabel(self.TituloEquipos)
        self.label.setGeometry(QtCore.QRect(40, 40, 151, 61))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono SemiBold")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color:gray;")
        self.label.setObjectName("label")
        self.ContEquipos = QtWidgets.QFrame(self.TituloEquipos)
        self.ContEquipos.setGeometry(QtCore.QRect(1, 100, 1081, 611))
        self.ContEquipos.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ContEquipos.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ContEquipos.setObjectName("ContEquipos")
        self.label_2 = QtWidgets.QLabel(self.ContEquipos)
        self.label_2.setGeometry(QtCore.QRect(20, 50, 81, 41))
        self.label_2.setStyleSheet("color:black;")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.ContEquipos)
        self.label_3.setGeometry(QtCore.QRect(300, 60, 111, 41))
        self.label_3.setStyleSheet("color:black;")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.ContEquipos)
        self.label_4.setGeometry(QtCore.QRect(630, 60, 58, 18))
        self.label_4.setStyleSheet("color:balck;")
        self.label_4.setObjectName("label_4")
        self.BtnInsertar = QtWidgets.QPushButton(self.ContEquipos)
        self.BtnInsertar.setGeometry(QtCore.QRect(940, 50, 101, 51))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.BtnInsertar.setFont(font)
        self.BtnInsertar.setStyleSheet("QPushButton{\n"
"    background-color: rgb(120, 208, 9);\n"
"    color:white;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:white;\n"
"    border-color:black;\n"
"    color:black;\n"
"}")
        self.BtnInsertar.setObjectName("BtnInsertar")
        self.TxtNombreEquipo = QtWidgets.QTextEdit(self.ContEquipos)
        self.TxtNombreEquipo.setGeometry(QtCore.QRect(110, 60, 171, 31))
        self.TxtNombreEquipo.setStyleSheet("color:black;")
        self.TxtNombreEquipo.setObjectName("TxtNombreEquipo")
        self.TxtRepresentanteEquipo = QtWidgets.QTextEdit(self.ContEquipos)
        self.TxtRepresentanteEquipo.setGeometry(QtCore.QRect(420, 60, 201, 31))
        self.TxtRepresentanteEquipo.setStyleSheet("color:black;")
        self.TxtRepresentanteEquipo.setObjectName("TxtRepresentanteEquipo")
        self.TxtCampoEquipo = QtWidgets.QTextEdit(self.ContEquipos)
        self.TxtCampoEquipo.setGeometry(QtCore.QRect(690, 60, 191, 31))
        self.TxtCampoEquipo.setStyleSheet("color:black;")
        self.TxtCampoEquipo.setObjectName("TxtCampoEquipo")
        self.BtnActualizar = QtWidgets.QPushButton(self.ContEquipos)
        self.BtnActualizar.setGeometry(QtCore.QRect(930, 220, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.BtnActualizar.setFont(font)
        self.BtnActualizar.setStyleSheet("QPushButton{\n"
"    background-color: rgb(120, 208, 9);\n"
"    color:white;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:white;\n"
"    border-color:black;\n"
"    color:black;\n"
"}")
        self.BtnActualizar.setObjectName("BtnActualizar")
        self.BtnBorrar = QtWidgets.QPushButton(self.ContEquipos)
        self.BtnBorrar.setGeometry(QtCore.QRect(940, 310, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.BtnBorrar.setFont(font)
        self.BtnBorrar.setStyleSheet("QPushButton{\n"
"    background-color: rgb(214, 44, 6);\n"
"    color:white;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:white;\n"
"    border-color:black;\n"
"    color:black;\n"
"}")
        self.BtnBorrar.setObjectName("BtnBorrar")
        self.tablaEquipos = QtWidgets.QTableWidget(self.ContEquipos)
        self.tablaEquipos.setEnabled(True)
        self.tablaEquipos.setGeometry(QtCore.QRect(20, 160, 861, 431))
        self.tablaEquipos.setStyleSheet("\n"
"    color:balck;\n"
"    font: 63 11pt \"Noto Sans Mono SemiBold\";\n"
"    text-align:center;\n"
"    border-color_black")
        self.tablaEquipos.setRowCount(0)
        self.tablaEquipos.setObjectName("tablaEquipos")
        self.tablaEquipos.setColumnCount(4)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(9)
        item.setFont(font)
        self.tablaEquipos.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablaEquipos.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablaEquipos.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablaEquipos.setHorizontalHeaderItem(3, item)
        self.tablaEquipos.horizontalHeader().setVisible(False)
        self.tablaEquipos.horizontalHeader().setDefaultSectionSize(220)
        self.btnlistar = QtWidgets.QPushButton(self.ContEquipos)
        self.btnlistar.setGeometry(QtCore.QRect(950, 410, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btnlistar.setFont(font)
        self.btnlistar.setStyleSheet("QPushButton{\n"
"    background-color: rgb(120, 208, 9);\n"
"    color:white;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:white;\n"
"    border-color:black;\n"
"    color:black;\n"
"}")
        self.btnlistar.setObjectName("btnlistar")
        self.BtnEmpezarTorneo = QtWidgets.QPushButton(self.ContEquipos)
        self.BtnEmpezarTorneo.setGeometry(QtCore.QRect(920, 510, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.BtnEmpezarTorneo.setFont(font)
        self.BtnEmpezarTorneo.setStyleSheet("QPushButton{\n"
"    background-color:  rgb(43, 98, 180);\n"
"    color:white;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:white;\n"
"    border-color:black;\n"
"    color:black;\n"
"}")
        self.BtnEmpezarTorneo.setObjectName("BtnEmpezarTorneo")
        self.horizontalLayout_4.addWidget(self.TituloEquipos)
        self.stackedWidget.addWidget(self.PaginaEquipos)
        self.PaginaTabla = QtWidgets.QWidget()
        self.PaginaTabla.setStyleSheet("QFrame{\n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.PaginaTabla.setObjectName("PaginaTabla")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.PaginaTabla)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.TituloTabla = QtWidgets.QFrame(self.PaginaTabla)
        self.TituloTabla.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.TituloTabla.setFrameShadow(QtWidgets.QFrame.Raised)
        self.TituloTabla.setObjectName("TituloTabla")
        self.label_5 = QtWidgets.QLabel(self.TituloTabla)
        self.label_5.setGeometry(QtCore.QRect(20, 50, 281, 51))
        self.label_5.setStyleSheet("color:gray;")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.TituloTabla)
        self.ContenidoTabla = QtWidgets.QFrame(self.PaginaTabla)
        self.ContenidoTabla.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ContenidoTabla.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ContenidoTabla.setObjectName("ContenidoTabla")
        self.TablaGeneral = QtWidgets.QTableWidget(self.ContenidoTabla)
        self.TablaGeneral.setGeometry(QtCore.QRect(10, 20, 1091, 551))
        self.TablaGeneral.setStyleSheet("    color:balck;\n"
"    font: 63 11pt \"Noto Sans Mono SemiBold\";\n"
"    text-align:center;\n"
"    border-color_black")
        self.TablaGeneral.setObjectName("TablaGeneral")
        self.TablaGeneral.setColumnCount(7)
        self.TablaGeneral.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.TablaGeneral.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaGeneral.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaGeneral.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaGeneral.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaGeneral.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaGeneral.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaGeneral.setHorizontalHeaderItem(6, item)

        self.TablaGeneral.setColumnWidth(0, 200)
        self.TablaGeneral.setColumnWidth(1, 150)
        self.TablaGeneral.setColumnWidth(2, 150)
        self.TablaGeneral.setColumnWidth(3, 150)
        self.TablaGeneral.setColumnWidth(4, 150)
        self.TablaGeneral.setColumnWidth(6, 200)
        self.TablaGeneral.setColumnWidth(7, 200)

        self.verticalLayout_4.addWidget(self.ContenidoTabla)
        self.verticalLayout_4.setStretch(0, 2)
        self.verticalLayout_4.setStretch(1, 8)
        self.stackedWidget.addWidget(self.PaginaTabla)
        self.PaginaJornada = QtWidgets.QWidget()
        self.PaginaJornada.setObjectName("PaginaJornada")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.PaginaJornada)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Titulo = QtWidgets.QWidget(self.PaginaJornada)
        self.Titulo.setAutoFillBackground(False)
        self.Titulo.setStyleSheet("background-color:white;\n"
"border-color: rgb(125, 125, 125);")
        self.Titulo.setObjectName("Titulo")
        self.TituloJornada = QtWidgets.QLabel(self.Titulo)
        self.TituloJornada.setGeometry(QtCore.QRect(50, 50, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono SemiBold")
        font.setBold(True)
        font.setWeight(75)
        self.TituloJornada.setFont(font)
        self.TituloJornada.setStyleSheet("color:gray;")
        self.TituloJornada.setObjectName("TituloJornada")
        self.BtnBuscarJornada = QtWidgets.QPushButton(self.Titulo)
        self.BtnBuscarJornada.setGeometry(QtCore.QRect(980, 60, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.BtnBuscarJornada.setFont(font)
        self.BtnBuscarJornada.setStyleSheet("QPushButton{\n"
"    background-color: rgb(120, 208, 9);\n"
"    color:white;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:white;\n"
"    border-color:black;\n"
"    color:black;\n"
"}")
        self.BtnBuscarJornada.setObjectName("BtnBuscarJornada")
        self.NumJornada = QtWidgets.QSpinBox(self.Titulo)
        self.NumJornada.setGeometry(QtCore.QRect(830, 60, 71, 41))
        self.NumJornada.setStyleSheet("color:black;")
        self.NumJornada.setObjectName("NumJornada")
        self.verticalLayout_3.addWidget(self.Titulo)
        self.ContJornada = QtWidgets.QWidget(self.PaginaJornada)
        self.ContJornada.setStyleSheet("background-color:white;")
        self.ContJornada.setObjectName("ContJornada")
        self.TablaPartidos = QtWidgets.QTableWidget(self.ContJornada)
        self.TablaPartidos.setGeometry(QtCore.QRect(40, 110, 1031, 371))
        self.TablaPartidos.setAutoFillBackground(False)
        self.TablaPartidos.setStyleSheet("    color:balck;\n"
"    font: 63 11pt \"Noto Sans Mono SemiBold\";\n"
"    text-align:center;\n"
"    border-color_black")
        self.TablaPartidos.setShowGrid(True)
        self.TablaPartidos.setWordWrap(True)
        self.TablaPartidos.setObjectName("TablaPartidos")
        self.TablaPartidos.setColumnCount(4)
        self.TablaPartidos.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.TablaPartidos.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaPartidos.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaPartidos.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaPartidos.setHorizontalHeaderItem(3, item)
        self.TablaPartidos.setColumnWidth(0, 250)
        self.TablaPartidos.setColumnWidth(1, 250)
        self.TablaPartidos.setColumnWidth(2, 250)
        self.TablaPartidos.setColumnWidth(3, 279)
        self.TablaPartidos.horizontalHeader().setVisible(True)
        self.TablaPartidos.horizontalHeader().setCascadingSectionResizes(False)
        self.TablaPartidos.horizontalHeader().setHighlightSections(True)
        self.TablaPartidos.horizontalHeader().setSortIndicatorShown(True)
        self.TablaPartidos.verticalHeader().setVisible(True)
        self.BtnAsignarResultado = QtWidgets.QPushButton(self.ContJornada)
        self.BtnAsignarResultado.setGeometry(QtCore.QRect(980, 50, 88, 34))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.BtnAsignarResultado.setFont(font)
        self.BtnAsignarResultado.setStyleSheet("QPushButton{\n"
"    background-color: rgb(120, 208, 9);\n"
"    color:white;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:white;\n"
"    border-color:black;\n"
"    color:black;\n"
"}")
        self.BtnAsignarResultado.setObjectName("BtnAsignarResultado")
        self.TxtResultado = QtWidgets.QTextEdit(self.ContJornada)
        self.TxtResultado.setGeometry(QtCore.QRect(770, 50, 151, 31))
        self.TxtResultado.setStyleSheet("color:black;")
        self.TxtResultado.setObjectName("TxtResultado")
        self.label_6 = QtWidgets.QLabel(self.ContJornada)
        self.label_6.setGeometry(QtCore.QRect(640, 50, 101, 31))
        self.label_6.setStyleSheet("color:black;")
        self.label_6.setObjectName("label_6")
        self.BtnActualizarDatos = QtWidgets.QPushButton(self.ContJornada)
        self.BtnActualizarDatos.setGeometry(QtCore.QRect(870, 510, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.BtnActualizarDatos.setFont(font)
        self.BtnActualizarDatos.setStyleSheet("QPushButton{\n"
"    background-color: rgb(120, 208, 9);\n"
"    color:white;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:white;\n"
"    border-color:black;\n"
"    color:black;\n"
"}")
        self.BtnActualizarDatos.setObjectName("BtnActualizarDatos")
        self.BtnTerminarJornada = QtWidgets.QPushButton(self.ContJornada)
        self.BtnTerminarJornada.setGeometry(QtCore.QRect(40, 513, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.BtnTerminarJornada.setFont(font)
        self.BtnTerminarJornada.setStyleSheet("QPushButton{\n"
"    \n"
"    background-color: rgb(43, 98, 180);\n"
"    color:white;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:white;\n"
"    border-color:black;\n"
"    color:black;\n"
"}")
        self.BtnTerminarJornada.setObjectName("BtnTerminarJornada")
        self.verticalLayout_3.addWidget(self.ContJornada)
        self.verticalLayout_3.setStretch(0, 2)
        self.verticalLayout_3.setStretch(1, 8)
        self.stackedWidget.addWidget(self.PaginaJornada)
        self.verticalLayout_2.addWidget(self.stackedWidget)
        self.horizontalLayout_2.addWidget(self.Contenido)
        self.verticalLayout.addWidget(self.General)
        self.horizontalLayout.addWidget(self.PrincipalFrame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Liga.setText(_translate("MainWindow", "Liga de futbol."))
        self.BtnTabla.setText(_translate("MainWindow", "Tabla General"))
        self.BtnEquipo.setText(_translate("MainWindow", "Equipos"))
        self.BtnJornada.setText(_translate("MainWindow", "Jornada"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Equipos</p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Nombre</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Representante</span></p><p align=\"center\"><span style=\" font-size:12pt;\"><br/></span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Campo</span></p></body></html>"))
        self.BtnInsertar.setText(_translate("MainWindow", "Insertar"))
        self.BtnActualizar.setText(_translate("MainWindow", "Actualizar"))
        self.BtnBorrar.setText(_translate("MainWindow", "Borrar"))
        item = self.tablaEquipos.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tablaEquipos.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Nombre"))
        item = self.tablaEquipos.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Representante"))
        item = self.tablaEquipos.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Campo"))
        self.btnlistar.setText(_translate("MainWindow", "Listar"))
        self.BtnEmpezarTorneo.setText(_translate("MainWindow", "Empezar Torneo"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt;\">Tabla General</span></p></body></html>"))
        item = self.TablaGeneral.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Equipo"))
        item = self.TablaGeneral.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "PJ"))
        item = self.TablaGeneral.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "PP"))
        item = self.TablaGeneral.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "PE"))
        item = self.TablaGeneral.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "PG"))
        item = self.TablaGeneral.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Goles"))
        item = self.TablaGeneral.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Puntos"))
        self.TituloJornada.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:22pt;\">Jornada</span></p></body></html>"))
        self.BtnBuscarJornada.setText(_translate("MainWindow", "Buscar"))
        item = self.TablaPartidos.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Local"))
        item = self.TablaPartidos.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Visitante"))
        item = self.TablaPartidos.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Campo"))
        item = self.TablaPartidos.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Resultado"))
        self.BtnAsignarResultado.setText(_translate("MainWindow", "Asignar"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">Resultado: </span></p></body></html>"))
        self.BtnActualizarDatos.setText(_translate("MainWindow", "Actualizar datos"))
        self.BtnTerminarJornada.setText(_translate("MainWindow", "Terminar Jornada"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
