# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventana_actualizar.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ActualizarWIndow(object):
    def setupUi(self, ActualizarWIndow):
        ActualizarWIndow.setObjectName("ActualizarWIndow")
        ActualizarWIndow.resize(605, 335)
        ActualizarWIndow.setStyleSheet("QWidget{\n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QLabel{\n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(ActualizarWIndow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 40, 51, 21))
        self.label.setObjectName("label")
        self.LabelID = QtWidgets.QLabel(self.centralwidget)
        self.LabelID.setGeometry(QtCore.QRect(170, 40, 131, 21))
        self.LabelID.setObjectName("LabelID")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 100, 81, 31))
        self.label_3.setObjectName("label_3")
        self.TxtNombre = QtWidgets.QTextEdit(self.centralwidget)
        self.TxtNombre.setGeometry(QtCore.QRect(140, 100, 191, 41))
        self.TxtNombre.setStyleSheet("color:black;")
        self.TxtNombre.setObjectName("TxtNombre")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 170, 131, 31))
        self.label_4.setObjectName("label_4")
        self.TxtRepresentante = QtWidgets.QTextEdit(self.centralwidget)
        self.TxtRepresentante.setGeometry(QtCore.QRect(180, 170, 211, 41))
        self.TxtRepresentante.setStyleSheet("color:black;")
        self.TxtRepresentante.setObjectName("TxtRepresentante")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(50, 250, 91, 31))
        self.label_5.setObjectName("label_5")
        self.TxtCampo = QtWidgets.QTextEdit(self.centralwidget)
        self.TxtCampo.setGeometry(QtCore.QRect(170, 240, 191, 41))
        self.TxtCampo.setStyleSheet("color:black;")
        self.TxtCampo.setObjectName("TxtCampo")
        self.BtnAceptar = QtWidgets.QPushButton(self.centralwidget)
        self.BtnAceptar.setGeometry(QtCore.QRect(460, 250, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.BtnAceptar.setFont(font)
        self.BtnAceptar.setStyleSheet("QPushButton{\n"
"    background-color: rgb(120, 208, 9);\n"
"    color:white;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:white;\n"
"    border-color:black;\n"
"    color:black;\n"
"}")
        self.BtnAceptar.setObjectName("BtnAceptar")
        ActualizarWIndow.setCentralWidget(self.centralwidget)

        self.retranslateUi(ActualizarWIndow)
        QtCore.QMetaObject.connectSlotsByName(ActualizarWIndow)

    def retranslateUi(self, ActualizarWIndow):
        _translate = QtCore.QCoreApplication.translate
        ActualizarWIndow.setWindowTitle(_translate("ActualizarWIndow", "MainWindow"))
        self.label.setText(_translate("ActualizarWIndow", "<html><head/><body><p><span style=\" font-size:12pt;\">ID: </span></p></body></html>"))
        self.LabelID.setText(_translate("ActualizarWIndow", "<html><head/><body><p>ID del equipo</p></body></html>"))
        self.label_3.setText(_translate("ActualizarWIndow", "<html><head/><body><p><span style=\" font-size:12pt;\">Nombre</span></p></body></html>"))
        self.label_4.setText(_translate("ActualizarWIndow", "<html><head/><body><p><span style=\" font-size:12pt;\">Representante: </span></p></body></html>"))
        self.label_5.setText(_translate("ActualizarWIndow", "<html><head/><body><p><span style=\" font-size:12pt;\">Campo</span></p></body></html>"))
        self.BtnAceptar.setText(_translate("ActualizarWIndow", "Aceptar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ActualizarWIndow = QtWidgets.QMainWindow()
    ui = Ui_ActualizarWIndow()
    ui.setupUi(ActualizarWIndow)
    ActualizarWIndow.show()
    sys.exit(app.exec_())
